apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe
spec:
  ingressClassName: traefik
  rules:
    - host: tictactoe.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe
                port:
                  number: 80
